### ISSUE TITLE
Running the app - setting up the profiles.clj

### ISSUE THREAD

**Issue by Okwori** [cnirrad/lacinia-test#1]
@cnirrad can you paste the content of your profiles.clj _(without the sensitive details of course)_, I am having issues setting up one and not the sure the version of Luminous this is.

**Comment by cnirrad** [comment]
I don't use one. What is the issue you are having?

**Comment by Okwori** [comment]
Well, I thought since you are using the earlier Luminous template, you had the DB configurations there.
I had issues running migrations/connecting to the DB...
